name: diff
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.28.0
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.1.1
      - cycler==0.12.1
      - diffusers==0.21.0
      - docker-pycreds==0.4.0
      - efficientnet-pytorch==0.7.1
      - filelock==3.13.1
      - fonttools==4.50.0
      - fsspec==2024.3.1
      - ftfy==6.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.28.2
      - google-auth-oauthlib==1.0.0
      - grpcio==1.62.1
      - huggingface-hub==0.21.4
      - idna==3.6
      - importlib-metadata==7.0.2
      - importlib-resources==6.3.2
      - jinja2==3.1.3
      - kiwisolver==1.4.5
      - lightning-utilities==0.11.2
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - oauthlib==3.2.2
      - packaging==24.0
      - pillow==10.2.0
      - platformdirs==4.2.1
      - protobuf==4.25.3
      - psutil==5.9.8
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - requests-oauthlib==1.4.0
      - rsa==4.9
      - safetensors==0.4.2
      - scipy==1.10.1
      - sentry-sdk==2.1.1
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - timm==0.9.16
      - tokenizers==0.13.3
      - torch==1.13.0
      - torch-fidelity==0.3.0
      - torchmetrics==1.4.0.post0
      - torchvision==0.14.0
      - tqdm==4.66.2
      - transformers==4.27.0
      - typing-extensions==4.10.0
      - urllib3==2.2.1
      - wandb==0.17.0
      - wcwidth==0.2.13
      - werkzeug==3.0.1
      - zipp==3.18.1
prefix: /hpc2hdd/home/mchenbt/.conda/envs/diff
